Add script for generating grammars.dat and setup CI
FrayxRulez/libprisma pull request #2
Opened 2023-10-22 01:26 UTC by STmihan

Rewrite generate.js a bit to make it work in node js, using some `eval` magic from [here](https://stackoverflow.com/a/23699187/17140794). To see the most important changes in the new generate script check https://github.com/STmihan/libprisma/commit/bde28aa8e798a25ba93beedd018800822ddc198c

I set up the workflow for publishing as an action artifact [example here](https://github.com/STmihan/libprisma/actions/runs/6600640871), but I right now looking on a https://github.com/TelegramMessenger/libprisma/pull/1 and it looks cool too.
If you think that [MarshalX's](https://github.com/MarshalX) variant is better, I can just add his PR workflow to my solution.

2023-10-22 01:40 UTC, STmihan commented
Okay, I just copied the workflow from #1, but I am not sure how to check that it does anything (because both `grammars.dat` are the same)

2023-10-26 12:07 UTC, FrayxRulez commented
Hey, this is exactly what I wanted to have.
I would say that it makes sense to just rename `generate-node.js` to `generate.js` and keep just this code :)
Only one thing I'd like to change: `isEqual.js` actually comes from a `npm` package: https://github.com/lodash/lodash/tree/4.5.0-npm-packages/lodash.isequal
Could you change your code to actually install and use that rather than the local copy? Thank you!

2023-10-26 20:53 UTC, STmihan commented
Done. I have created an npm repo, added "lodash.isequal" as a dependency, and updated README.md from the master

2023-10-27 09:56 UTC, FrayxRulez requested changes

2023-10-27 09:56 UTC, FrayxRulez commented on package.json
> +  "main": "generate-node.js",
```suggestion
  "main": "generate.js",
```

2023-10-30 13:41 UTC, merged

2025-10-16 23:49 UTC, Phi242 commented
A

2025-10-16 23:50 UTC, Phi242 approved these changes

2025-10-16 23:51 UTC, Phi242 commented on package.json
> +  "main": "generate-node.js",
Yy

2025-10-16 23:52 UTC, Phi242 requested changes
Fh